// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpAddressQrCode():Promise<string>;

export function GetLocalIpAddress():Promise<string>;
