// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIpAddressQrCode() {
  return window['go']['main']['App']['GetIpAddressQrCode']();
}

export function GetLocalIpAddress() {
  return window['go']['main']['App']['GetLocalIpAddress']();
}
