name: Build/release

on: push

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.4'
      - name: Install C complier
        run: |
          pacman -Syu
          pacman -S git mingw-w64-x86_64-toolchain
      - name: Set Path
        run: echo "export PATH=\$PATH:/c/Program\ Files/Go/bin:~/Go/bin" >> ~/.bashrc
      - name: "Install dependencies"
        working-directory: .\fyne-netflix-remote
        run: |
          go mod tidy
          go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: "build binary"
        working-directory: .\fyne-netflix-remote
        run: fyne package -icon assets/icon.ico -name netflix-remote -appVersion 1.0.0 -appID io.netflix-remote -release