name: Build/release

on: push

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        run: |
          wget -P c https://netix.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7zhttps://netix.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z
          7z x c://x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z mingw
          cd c://mingw
          dir .
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.4'
      - name: "Install dependencies"
        working-directory: .\fyne-netflix-remote
        run: |
          go mod tidy
          go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: "build binary"
        working-directory: .\fyne-netflix-remote
        run: fyne package -icon assets/icon.ico -name netflix-remote -appVersion 1.0.0 -appID io.netflix-remote -release
